"""Sync schema

Revision ID: 8fe4dcd0cc61
Revises: 13ea1c8f5777
Create Date: 2025-12-13 09:05:27.193225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '8fe4dcd0cc61'
down_revision: Union[str, None] = '13ea1c8f5777'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_owners', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        # batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_account_owners_account_id', 'accounts', ['account_id'], ['id'])
        batch_op.create_foreign_key('fk_account_owners_owner_id', 'owners', ['owner_id'], ['id'])

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.alter_column('tax_wrapper',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.Enum('NONE', 'ISA', 'LISA', 'PENSION', 'GIA', name='taxwrapper'),
               existing_nullable=True)
        batch_op.alter_column('unit_price',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('is_primary_account',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        # batch_op.drop_index('ix_accounts_name')
        # batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_accounts_scenario_id', 'scenarios', ['scenario_id'], ['id'])

    with op.batch_alter_table('automation_rules', schema=None) as batch_op:
        batch_op.alter_column('trigger_value',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('transfer_cap',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('priority',
               existing_type=sa.INTEGER(),
               nullable=True)
        # batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_automation_rules_scenario_id', 'scenarios', ['scenario_id'], ['id'])

    with op.batch_alter_table('costs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('growth_rate', sa.Float(), nullable=True))
        # batch_op.drop_index('ix_costs_name')
        # batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_costs_scenario_id', 'scenarios', ['scenario_id'], ['id'])

    with op.batch_alter_table('financial_events', schema=None) as batch_op:
        # batch_op.drop_index('ix_financial_events_name')
        # batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_financial_events_scenario_id', 'scenarios', ['scenario_id'], ['id'])

    with op.batch_alter_table('income_sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('growth_rate', sa.Float(), nullable=True))
        # batch_op.drop_index('ix_income_sources_name')
        # batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_income_sources_owner_id', 'owners', ['owner_id'], ['id'])

    with op.batch_alter_table('owners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('retirement_age', sa.Integer(), nullable=True))
        # batch_op.drop_index('ix_owners_name')
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_owners_scenario_id', 'scenarios', ['scenario_id'], ['id'])

    with op.batch_alter_table('scenario_history', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)

    with op.batch_alter_table('tax_limits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frequency', sa.String(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('wrappers',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               nullable=True)
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_tax_limits_scenario_id', 'scenarios', ['scenario_id'], ['id'])

    with op.batch_alter_table('transfers', schema=None) as batch_op:
        # batch_op.drop_index('ix_transfers_name')
        # batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_transfers_scenario_id', 'scenarios', ['scenario_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    pass 
