"""Add vesting_cadence to accounts

Revision ID: e82fcb744a84
Revises: f9e5bef97330
Create Date: 2025-12-22 18:10:40.304576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e82fcb744a84'
down_revision: Union[str, None] = 'f9e5bef97330'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###