"""Add employer_pension_contribution to IncomeSource

Revision ID: f4dea42aca55
Revises: b0504df00c42
Create Date: 2025-12-05 05:37:11.797892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4dea42aca55'
down_revision: Union[str, None] = 'b0504df00c42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income_sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employer_pension_contribution', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income_sources', schema=None) as batch_op:
        batch_op.drop_column('employer_pension_contribution')

    # ### end Alembic commands ###