"""Add missing columns

Revision ID: fac123456789
Revises: e82fcb744a84
Create Date: 2025-12-23 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fac123456789'
down_revision: Union[str, None] = 'e82fcb744a84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('is_primary_account', sa.Boolean(), nullable=True, default=False))
    # SQLite doesn't support adding column with default well, usually nullable is easier.
    # But here I set nullable=True.

    op.add_column('automation_rules', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automation_rules', schema=None) as batch_op:
        batch_op.drop_column('notes')

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('is_primary_account')
    # ### end Alembic commands ###
